{% set version = "0.6.2" %}

package:
  name: cgat-apps
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cgat/cgat-{{ version }}.tar.gz
  sha256: e7d6852f69409ce7c325bb913cffd04edaa9df5e8e75f7d35c378017c9561c8a


build:
  skip: True # [not py3k]
  number: 0
  entry_points:
    - cgat = cgat.cgat:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - cython
    - numpy
    #- pysam<=0.15.2
    - htslib
    - setuptools
    - coreutils
    - libpng
    - zlib

  run:
    - python
    - cgatcore>=0.6.5
    - alignlib-lite
    #- biopython<=1.77
    - future
    - matplotlib-base
    - {{ pin_compatible('numpy') }}
    - pandas
    - pybedtools
    - pybigwig
    #- pysam<=0.15.2
    - htslib
    - python-lzo
    - pyyaml
    - quicksect
    - scipy
    - scikit-learn
    - six
    - sortedcontainers
    # Misc dependencies
    - bedtools
    - ucsc-bedgraphtobigwig
    - ucsc-bedtobigbed
    - ucsc-wigtobigwig
    - coreutils
    - grep
    - libpng

test:
  imports:
    - cgat

  commands:
    - cgat --help
    - cgat --help Conversion
    - cgat gtf2table -h
    - find ${PREFIX} -iname "*bamtools.cpython-*-x86_64-linux-gnu.so*" -exec ldd {} \;
    - cgat bam2bed -h

about:
  home: https://www.cgat.org/downloads/public/cgat/documentation
  license: MIT
  license_file: LICENSE
  summary: "Computational Genomics Analysis Toolkit"
