{% set name = "ntm-profiler" %}
{% set version = "0.1.0" %}
{% set sha256 = "1190928dd06122f31caf01b610f468141aaf1f0f2e83062fb4092cb8a7f5ddeb" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/jodyphelan/NTM-Profiler/archive/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - python>=3.6
    - pip
  run:
    - python>=3.6
    - dsk
    - tqdm


test:
  imports:
    - ntm_profiler

  commands:
    - ntm-profiler -h

about:
  home: https://github.com/jodyphelan/NTM-Profiler
  license: GPL3
  license_file: LICENSE
  summary: Profiling tool for NTM to detect species from WGS data
