{% set name = "bifrost" %}
{% set version = "1.0.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/pmelsted/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: cbcbf465d94665af6a8a7164a81a141a5c7c761f57f0f31d06b60a5d09f4738f

build:
  number: 0

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
  host:
    - zlib
    - pthread-stubs
  run:
    - zlib
    - pthread-stubs

test:
  commands:
    - Bifrost --version

about:
   home: https://github.com/pmelsted/bifrost
   license: BSD-2-Clause
   license_family: BSD
   license_file: LICENSE
   summary: Highly parallel construction and indexing of colored and compacted de Bruijn graphs

extra:
   identifiers:
     - doi:10.1101/695338
