{% set name = "AquilaSV" %}
{% set version = "1.1" %}

package:
  name: "aquila_sv"
  version: "{{ version }}"

source:
  url: https://github.com/maiziezhoulab/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: ba7de0ebf5c8c933befe22710dec5971f32ee1d96773452aacc547d77916bd9e

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python >=3
    - setuptools

  run:
    - python >=3
    - setuptools
    - samtools
    - pysam
    - minimap2
    - scipy
    - numpy

test:
  commands:
    - AquilaSV_step1 --help
    - AquilaSV_step2 --help
    - AquilaSV_step3 --help


about:
  home: https://github.com/maiziezhoulab/AquilaSV
  license: MIT
  license_file: LICENSE
  summary: Diploid assembly and variants calling tool
