{% set name = "snakeSV" %}
{% set version = "0.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/RajLabMSSM/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 7339e80200a6e544a5763caf429ded562b9500800613de90dfdc6855c684f520

build:
  number: 0
  noarch: generic

requirements:
  run:
    - snakemake >=6.5.2
    - mamba >=0.14.1
    - pandas >=1.3.0

test:
  commands:
    - snakeSV -h

about:
  home: https://github.com/RajLabMSSM/snakeSV/
  license: "The MIT License (MIT)"
  summary: "snakeSV: Flexible framework for large-scale SV discovery"

