{% set name = "perl-extutils-makemaker" %}
{% set version = "7.64" %}
{% set sha256 = "4a6ac575815c0413b1f58967043cc9f2e166446b73c687f9bc62b5eaed9464a0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0

requirements:
  build:
    - make
  host:
    - perl

  run:
    - perl

test:
  imports:
    - ExtUtils::Command
    - ExtUtils::Command::MM
    - ExtUtils::Liblist
    - ExtUtils::Liblist::Kid
    - ExtUtils::MM
    - ExtUtils::MM_AIX
    - ExtUtils::MM_Any
    - ExtUtils::MM_BeOS
    - ExtUtils::MM_Cygwin
    - ExtUtils::MM_DOS
    - ExtUtils::MM_Darwin
    - ExtUtils::MM_MacOS
    - ExtUtils::MM_NW5
    - ExtUtils::MM_OS2
    - ExtUtils::MM_QNX
    - ExtUtils::MM_UWIN
    - ExtUtils::MM_Unix
    - ExtUtils::MM_VMS
    - ExtUtils::MM_VOS
    - ExtUtils::MM_Win32
    - ExtUtils::MM_Win95
    - ExtUtils::MY
    - ExtUtils::MakeMaker
    - ExtUtils::MakeMaker::Config
    - ExtUtils::MakeMaker::Locale
    - ExtUtils::MakeMaker::version
    - ExtUtils::MakeMaker::version::regex
    - ExtUtils::MakeMaker::version::vpp
    - ExtUtils::Mkbootstrap
    - ExtUtils::Mksymlists
    - ExtUtils::testlib

about:
  home: https://metacpan.org/release/ExtUtils-MakeMaker
  license: perl_5
  summary: 'Create a module Makefile'
