{% set name = "tb-profiler" %}
{% set version = "4.0.0" %}
{% set sha256 = "53e8e4a4e219e05c7612cd81597afe4383d9e20b293aa7f66c485c53f5866535" %}

package:
  name: {{name}}
  version: {{version}}

source:
  url: https://github.com/jodyphelan/TBProfiler/archive/v{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  noarch: python
  number: 1

requirements:
  host:
    - python
    - pip
    - gatk4
    - samtools=1.10
    - bwa
  run:
    - python>=3.6
    - git
    - trimmomatic
    - bwa
    - bowtie2
    - minimap2
    - parallel
    - samtools=1.10
    - bcftools=1.10
    - tqdm
    - delly=0.8.7
    - gatk4
    - bedtools
    - freebayes
    - samclip
    - snpeff=4.3
    - requests

test:
  imports:
    - tbprofiler
    - pathogenprofiler
  commands:
    - tb-profiler -h
    - echo '#' | rename_vcf_chrom.py
    - echo '#' | combine_vcf_variants.py 
    - echo '#' | add_dummy_AD.py

about:
  home: https://github.com/jodyphelan/TBProfiler
  license: GPL3
  license_file: LICENSE
  summary: Profiling tool for Mycobacterium tuberculosis to detect drug resistance and lineage from WGS data

extra:
  identifiers:
    - doi:10.1186/s13073-019-0650-x
