{% set version = "1.20.0" %}
{% set name = "FlowSorted.CordBloodNorway.450k" %}
{% set bioc = "3.14" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/src/contrib/{{ name }}_{{ version }}.tar.gz'
  md5: 97eb3352d1035866f1e2b8fa13f1011b
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
requirements:
  host:
    - 'bioconductor-minfi >=1.40.0,<1.41.0'
    - r-base
  run:
    - 'bioconductor-minfi >=1.40.0,<1.41.0'
    - r-base
    - curl
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/data/experiment/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Illumina HumanMethylation data on sorted cord blood cell populations'
  description: 'Raw data objects for the Illumina 450k DNA methylation microarrays, for cell type composition estimation.'

