{% set name = "mummer" %}
{% set version = "3.23" %}
{% set sha256 = "1efad4f7d8cee0d8eaebb320a2d63745bb3a160bb513a15ef7af46f330af662f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  #url: https://downloads.sourceforge.net/project/mummer/mummer/{{ version }}/MUMmer{{ version }}.tar.gz
  url: "https://downloads.sourceforge.net/project/mummer/mummer/3.23/MUMmer3.23.tar.gz?ts=gAAAAABh5I3B9C1Ijram26w_mvS-G7o52dq870uU5PvqJQGWnKmh4tUVeTemTi0lnO0lgVGq7CKbelTFkYq1E0k1fovOtE5NSw%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fmummer%2Ffiles%2Fmummer%2F3.23%2FMUMmer3.23.tar.gz%2Fdownload%3Fuse_mirror%3Dkumisystems"
  sha256: {{ sha256 }}
  patches:
    - patches/gnuplot_mouse_clipboardformat.patch

build:
  number: 13

requirements:
  build:
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl # [not osx]
  run:
    - perl # [not osx]

test:
  commands:
    - "mummer -h &> /dev/null"
    #- "delta-filter -h &> /dev/null"
    #- "dnadiff -h &> /dev/null"
    #- "mapview -h &> /dev/null"
    - "mummerplot -h &> /dev/null"
    - "nucmer -h &> /dev/null"
    - "promer -h &> /dev/null"
    - "show-aligns -h &> /dev/null"
    #- "show-coords -h &> /dev/null"
    #- "show-diff -h &> /dev/null"
    #- "show-snps -h &> /dev/null"
    #- "show-tiling -h &> /dev/null"

about:
  home: 'http://mummer.sourceforge.net/'
  license: "The Artistic License"
  license_file: LICENSE
  summary: "MUMmer is a system for rapidly aligning entire genomes"

extra:
  identifiers:
    - biotools:mummer
