{% set version = "1.1.1" %}

package:
  name: nopilesum
  version: '{{ version }}'

source:
  url: https://github.com/blachlylab/nopilesum/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 66da184677e6a3ce50b00dcf1f55cf0b21f17882cd39a9ae9cb661e148a8ee8f


build:
  number: 0
  # binary_relocation: False # [linux]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - htslib
  run:
    - htslib

test:
  commands:
    - nopilesum
  
about:
  home: https://github.com/blachlylab/nopilesum
  license: MIT
  summary: "nopilesum is a D program that functions as an alternative to GATK4's GetPileupSummaries."



